arb-dir: lib/l10n
template-arb-file: app_ar.arb

output-localization-file: app_localizations.dart

supported-locales:
- en
- ar

translate: false                             # Enable translation 
key-prefix: t(context).   # Key prefix for translation
import-line: ""                             # Import line if needed
auto-name-key: false                        # Generate key name based on text
generate : true                             # auto run flutter gen-l10n
